Created New Owner Inquiry Page
infinite-options/manifestmyspace-web pull request #59
Opened 2023-10-23 11:47 UTC by rohitkphilip

2023-10-23 15:58 UTC, adityabaravkar requested changes

2023-10-23 15:58 UTC, adityabaravkar commented on package.json
I think React picks up properties in .env without the need for dotenv.

2023-10-23 15:58 UTC, adityabaravkar commented on src/components/Contracts/OwnerManagerContracts/NewOwnerInquiry.jsx
> +        const response = await fetch(`https://l0h6a9zi1e.execute-api.us-west-1.amazonaws.com/dev/properties/600-000003`)
Dynamic profile UID

2023-10-23 16:17 UTC, rohitkphilip commented on package.json
Ok. I removed it.

2023-10-24 13:33 UTC, adityabaravkar commented on package-lock.json
Can you undo the changes of package-lock.json?

2023-10-26 13:37 UTC, closed without merging